# Style
font_size=20
round_corners=10
background_alpha=0.7
position=top-right
table_columns=3
no_display
background_color=242f3b
gpu_color=8bbb65
cpu_color=5c87bb
vram_color=b066b9
ram_color=5ba0b7
engine_color=c3514f

# Component monitoring
cpu_stats
cpu_temp
gpu_stats
gpu_temp
gpu_mem_temp
pci_dev=0:03:00.0
vram
ram
ram_temp

# Frame monitoring
fps
frame_timing
show_fps_limit
fps_limit_method=late
fps_limit=0,60,120

# Performance
gamemode
vsync=3
gl_vsync=n

# Logging
autostart_log=0
output_folder=~/.config/MangoHud
log_duration=30

# Key bindings
toggle_fps_limit=Shift_L+F1
toggle_logging=Shift_L+F2
upload_log=Shift_L+F3
reload_cfg=Shift_L+F4
reset_fps_metrics=Shift_R+F9
toggle_preset=Shift_R+F10
toggle_hud_position=Shift_R+F11
toggle_hud=Shift_R+F12
