
#  _    _ _   _
# | |  (_) | | |
# | | ___| |_| |_ _   _
# | |/ / | __| __| | | |
# |   <| | |_| |_| |_| |
# |_|\_\_|\__|\__|\__, |
#                  __/ |
#                 |___/

include colorscheme.conf

shell fish

# Fonts

font_size 11

font_family      monospace
bold_font        auto
italic_font      auto
bold_italic_font auto

font_family      CaskaydiaCove Nerd Font Mono
bold_font        CaskaydiaCove Nerd Font Mono Bold
italic_font      CaskaydiaCove Nerd Font Mono Italic
bold_italic_font CaskaydiaCove Nerd Font Mono Bold Italic

disable_ligatures never

# Mouse

mouse_hide_wait 3.0

detect_urls yes
url_color #4586c4
url_style straight
open_url_with default
url_prefixes file ftp ftps gemini git gopher http https irc ircs kitty mailto news sftp ssh
underline_hyperlinks hover

# Performance tuning

sync_to_monitor yes

# Window layout

window_padding_width 4

# Tab bar

tab_bar_edge bottom
tab_bar_style powerline
tab_bar_align left
tab_bar_min_tabs 2

active_tab_foreground   #c2ddff
active_tab_background   #4586c4
active_tab_font_style   bold-italic
inactive_tab_foreground #bdd3ef
inactive_tab_background #34465c
inactive_tab_font_style normal
