gui:
  scrollPastBottom: false
  showBottomLine: false
  showRandomTip: false
  showCommandLog: false
  fileTreeSortOrder: foldersFirst
  theme:
    activeBorderColor:
    - 'blue'
    - bold
    inactiveBorderColor:
    - 'black'
    - bold
    selectedLineBgColor:
    - 'black'
    searchingActiveBorderColor:
    - 'blue'
    - bold
  authorColors:
    '*': 'yellow'
