[mgr]
cwd = { fg = "lightcyan" }

border_symbol = "│"
border_style = { fg = "darkgray" }

[mode]
normal_main = { fg = "black", bg = "lightblue", bold = true }
normal_alt = { fg = "lightblue", bg = "darkgray" }
