format = """
$directory\
$git_branch\
$git_status\
$cmd_duration\
$line_break\
$character
"""

[character]
success_symbol = "[❯](bright-green)"
error_symbol = "[❯](bright-red)"
vimcmd_symbol = "[❮](bright-yellow)"

[directory]
format = "[$path]($style) "
style = "bright-blue"
truncate_to_repo = false

[git_branch]
format = "[$symbol $branch]($style)"
style = "bright-purple"
symbol = "󰊢"

[git_status]
format = "[(•$conflicted$untracked$modified$staged$renamed$deleted) ($stashed$ahead_behind)]($style)"
style = "bright-purple"
conflicted = "​"
ahead = "[↑${count} ](bright-green)"
behind = "[↓${count} ](bright-red)"
diverged = ""
untracked = "​"
stashed = "[≡ ](bright-cyan)"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"

[cmd_duration]
format = "[$duration]($style)"
style = "italic yellow"
