format = """
$directory\
$git_branch\
$git_status\
$cmd_duration\
$line_break\
$character
"""

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold green)"

[directory]
format = "[$path]($style) "
style = "bold blue"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = false

[git_branch]
format = "[$symbol $branch]($style)"
style = "bold purple"
symbol = "󰊢"

[git_status]
format = "[(•$conflicted$untracked$modified$staged$renamed$deleted) ($ahead_behind$stashed)]($style)"
style = "bold purple"
conflicted = "​"
ahead = "[↑${count} ](bold green)"
behind = "[↓${count} ](bold red)"
diverged = ""
untracked = "​"
stashed = "[≡ ](bold yellow)"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"

[cmd_duration]
format = "[$duration]($style)"
style = "bold black"
